//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IValidationAttributeAdapterProviderSample.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IValidationAttributeAdapterProviderSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {1}では&apos;{0}&apos;は無効な値です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_AttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_AttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に対する値が指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_MissingBindRequiredValue {
            get {
                return ResourceManager.GetString("ModelBinding_MissingBindRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_MissingKeyOrValue {
            get {
                return ResourceManager.GetString("ModelBinding_MissingKeyOrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要求にボディの指定が必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_MissingRequestBodyRequiredValue {
            get {
                return ResourceManager.GetString("ModelBinding_MissingRequestBodyRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos;は無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_NonPropertyAttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_NonPropertyAttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値は無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_NonPropertyUnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_NonPropertyUnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数字を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_NonPropertyValueMustBeANumber {
            get {
                return ResourceManager.GetString("ModelBinding_NonPropertyValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の値は無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_UnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_UnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos;は無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_ValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は数字を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_ValueMustBeANumber {
            get {
                return ResourceManager.GetString("ModelBinding_ValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos;は無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelBinding_ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ModelBinding_ValueMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom message: Input the valid mail address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationMessageForEmailAddressAttribute {
            get {
                return ResourceManager.GetString("ValidationMessageForEmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom message: The length of {0} must be less than or equal to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationMessageForMaxLengthAttribute {
            get {
                return ResourceManager.GetString("ValidationMessageForMaxLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom message: The length of {0} must be greater than or equal to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationMessageForMinLengthAttribute {
            get {
                return ResourceManager.GetString("ValidationMessageForMinLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom message: {0} is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationMessageForRequiredAttribute {
            get {
                return ResourceManager.GetString("ValidationMessageForRequiredAttribute", resourceCulture);
            }
        }
    }
}
